#-Basic info----------------------------------------------------------------------------------------
name: ariba_plasmidfinder
version: 2.0
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: plasmid
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: recommended
  description: >
    This preforms read based mapping against the plasmidfinder DB's. The options show the species entries 
    which will be attempted for mlst with key originating from the species DB. This is done against 
    the cge_db using ariba.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-ariba_plasmidfinder:2.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "/bifrost_resources/plasmidfinder/ref_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      datafiles:
        paired_reads:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
    - "ariba_plasmidfinder/plasmid/report.tsv"
  sample:
    properties:
      plasmid:
        summary: 
        component:
          _id: 
          date: "ObjectId"
    report:
      plasmid:
        title: Plasmid
        info: *dockerfile
        columns:  # headers, these values are statically present in datadump
          - {id: "gene", name: "gene"}
          - {id: "coverage", name: "%cov"}
          - {id: "identity", name: "%id"}
          - {id: "variants", name: "# of variants"}
        data: []  # list of dicts parsed in datadump
  sample_component:
    summary:
    results:
      ariba_plasmidfinder/plasmid/report.tsv: {}
#---------------------------------------------------------------------------------------------------
