#-Basic info----------------------------------------------------------------------------------------
display_name: ariba_plasmidfinder
name: &name ariba_plasmidfinder__unspecified__unspecified
version:
  schema: 2.0
  code: unspecified
  resource: unspecified
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: sample
  description: >
    This preforms read based mapping against the plasmidfinder DB's. The options show the species entries 
    which will be attempted for mlst with key originating from the species DB. This is done against 
    the cge_db using ariba.
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [plasmid]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_ariba_plasmidfinder:unspecified__unspecified
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "/bifrost_ariba_plasmidfinder/resources/plasmidfinder/ref_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      paired_reads:
        summary:
          data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
    - "ariba_plasmidfinder/plasmid/report.tsv"
  sample:
    properties:
      plasmid:
        summary: 
        component:
          _id: 
          date: "ObjectId"
    report:
      plasmid:
        title: Plasmid
        info: *name
        columns:  # headers, these values are statically present in datadump
          - {id: "gene", name: "gene"}
          - {id: "coverage", name: "%cov"}
          - {id: "identity", name: "%id"}
          - {id: "variants", name: "# of variants"}
        data: []  # list of dicts parsed in datadump
  sample_component:
    summary:
    results:
      ariba_plasmidfinder/plasmid/report.tsv: {}
#---------------------------------------------------------------------------------------------------
